services:
  server:
    build:
      context: .
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_BASE_URL=${API_BASE_URL}
      - ENABLE_MOCK_API=${ENABLE_MOCK_API}
      - LOGTAIL_SOURCE_TOKEN=${ENABLE_MOCK_API}
      - LOGTAIL_INGESTING_HOST=${ENABLE_MOCK_API}
    ports:
      - 3000:3000
