name: 'Terraform Plan'

on:
    workflow_dispatch:
    pull_request:
        branches: [master]
        paths: ['terraform/**']

env:
    TF_CLOUD_ORGANIZATION: 'PowerCord'
    TF_WORKSPACE: 'powercord-bot'
    CONFIG_DIRECTORY: './terraform'

jobs:
    checkov-scan:
        name: 'Checkov Scan'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Run Checkov
              uses: bridgecrewio/checkov-action@v12
              with:
                  directory: ${{ env.CONFIG_DIRECTORY }}
                  framework: terraform
                  output_format: cli,sarif
                  output_file_path: console,checkov.sarif
                  soft_fail: true
            - name: Upload SARIF report
              uses: github/codeql-action/upload-sarif@v4
              with:
                  sarif_file: checkov.sarif

    terraform-plan:
        name: 'Terraform Plan'
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Upload Configuration
              uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
              id: plan-upload
              env:
                  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
              with:
                  workspace: ${{ env.TF_WORKSPACE }}
                  directory: ${{ env.CONFIG_DIRECTORY }}
                  speculative: true

            - name: Create Plan Run
              uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
              id: plan-run
              env:
                  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
              with:
                  workspace: ${{ env.TF_WORKSPACE }}
                  configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
                  plan_only: true
